### ISSUE TITLE
Upgrade to @materializecss/materialize v2.0.3-alpha to Enhance UI Manager

### ISSUE THREAD

**Issue by thkruz** [thkruz/keeptrack.space#707]
### User Story
- **As a** developer,
- **I want** to upgrade to `@materializecss/materialize` version `2.0.3-alpha`,
- **So that** we can leverage new features to improve the user interface for end-users.

### Acceptance Criteria
- **Given** the current project setup with `@materializecss/materialize` version `X.X.X`,
- **When** I replace the current version with `2.0.3-alpha`,
- **Then** I should be able to refactor the UI Manager code to ensure compatibility and to leverage the new features.

### Tasks
- [ ] Identify the areas in the UI Manager code which will be affected by the upgrade.
- [ ] Upgrade `@materializecss/materialize` to version `2.0.3-alpha` in a feature branch.
- [ ] Refactor the affected areas in the UI Manager code.
- [ ] Test the upgraded setup to ensure that all features work as expected.
- [ ] Document the changes made, particularly noting any breaking changes and new features leveraged.
- [ ] Merge the feature branch into the main branch after thorough testing and review.

### Commentary
- The new version `2.0.3-alpha` of `@materializecss/materialize` brings a host of new features which can be very beneficial in enhancing the user interface. We need to ensure that the upgrade does not break existing functionalities and is tested thoroughly before merging into the main branch.
- It might be beneficial to have front-end developers familiar with Materialize CSS to work on this task to ensure smooth transition and effective leveraging of the new features.

**Comment by thkruz** [comment]
I was able to update to 1.2. There are some issues importing v2 which is essentially a completely different package forked from the original.

**Comment by thkruz** [comment]
Done. Shipped on @materializecss/materialize ^2.3.3 (the issue asked for 2.0.3-alpha; we went to the stable v2.3.x line). Safe to close.
